#!/bin/bash
# License: This file is under LGPL v3. See LICENSE file distributed with this file.
# Author: Jacques Bodin-Hullin <j.bodinhullin@monsieurbiz.com)

echo "Title of your presentation?"
read title

# Create directories
if [[ ! -d css ]]; then
    echo "Create css/"
    mkdir css
fi

if [[ ! -d js ]]; then
    echo "Create js/"
    mkdir js
fi

if [[ ! -d img ]]; then
    echo "Create img/"
    mkdir img
fi

if [[ ! -f 'js/impress.js' ]]; then
    echo "Download js/impress.js"
    wget -q --no-check-certificate https://raw.github.com/bartaz/impress.js/master/js/impress.js -O js/impress.js
fi

if [[ ! -f 'css/default.css' ]]; then
    echo "Create css/default.css"
    cat > css/default.css <<EOF

/** CSS reset **/
/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
/** End of CSS reset **/

/* Default styles */
b, strong { font-weight: bold }
i, em { font-style: italic }

/* Links */
a {
    color: inherit;
    text-decoration: none;
    padding: 0 0.1em;
    background: rgba(255,255,255,0.5);
    text-shadow: -1px -1px 2px rgba(100,100,100,0.9);
    border-radius: 0.2em;

    -webkit-transition: 0.5s;
    -moz-transition:    0.5s;
    -ms-transition:     0.5s;
    -o-transition:      0.5s;
    transition:         0.5s;
}
a:hover,
a:focus {
    background: rgba(255,255,255,1);
    text-shadow: -1px -1px 2px rgba(100,100,100,0.5);
}

/* Fallback message */
.fallback-message {
    font-family: sans-serif;
    line-height: 1.3;

    width: 780px;
    padding: 10px 10px 0;
    margin: 20px auto;

    border: 1px solid #E4C652;
    border-radius: 10px;
    background: #EEDC94;
}

.fallback-message p {
    margin-bottom: 10px;
}

.impress-supported .fallback-message {
    display: none;
}

/** Your presentation's styles **/
body {
}

.impress-supported .step {
}

EOF
fi

if [[ ! -f 'index.html' ]]; then
    echo "Create index.html"
    cat > index.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>${title}</title>
    <link rel="stylesheet" href="css/default.css" />
</head>
<body class="impress-not-supported">

<!-- Not supported? -->
<div class="fallback-message">
    <p>Your browser <b>doesn't support the features required</b> by impress.js, so you are presented with a simplified version of this presentation.</p>
    <p>For the best experience please use the latest <b>Chrome</b>, <b>Safari</b> or <b>Firefox</b> browser.</p>
</div>

<div id="impress">

    <!-- Presentation -->
    <!-- *********************************************************************************** -->

    <div class="step" date-x="" data-y="" data-scale="1" data-rotate="" data-rotate-x="" data-rotate-y="">
        <h1>${title}</h1>
        <p>My First step</p>
    </div>

    <!-- *********************************************************************************** -->

</div>

<!-- Impress :') -->
<script src="js/impress.js"></script>
<script>impress().init();</script>

</body>
</html>
EOF
fi

echo "All good! Impress now ;)"
