#!/bin/bash
# License: This file is under LGPL v3. See LICENSE file distributed with this file.
# Author: Jacques Bodin-Hullin <j.bodinhullin@monsieurbiz.com)

echo "Title of your presentation?"
read title

# Create directories
if [[ ! -d css ]]; then
    echo "Create css/"
    mkdir css
fi

if [[ ! -d js ]]; then
    echo "Create js/"
    mkdir js
fi

if [[ ! -d img ]]; then
    echo "Create img/"
    mkdir img
fi

if [[ ! -f 'js/impress.js' ]]; then
    echo "Download js/impress.js"
    wget -q --no-check-certificate https://raw.github.com/bartaz/impress.js/master/js/impress.js -O js/impress.js
fi

if [[ ! -f 'css/default.css' ]]; then
    echo "Create css/default.css"
    cat > css/default.css <<EOF

/** CSS reset **/
/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
	display: block;
}
body {
	line-height: 1;
}
ol, ul {
	list-style: none;
}
blockquote, q {
	quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}
table {
	border-collapse: collapse;
	border-spacing: 0;
}
/** End of CSS reset **/

/* Default styles */
b, strong { font-weight: bold }
i, em { font-style: italic }

/* Links */
a {
    color: inherit;
    text-decoration: none;
    padding: 0 0.1em;
    background: rgba(255,255,255,0.5);
    text-shadow: -1px -1px 2px rgba(100,100,100,0.9);
    border-radius: 0.2em;

    -webkit-transition: 0.5s;
    -moz-transition:    0.5s;
    -ms-transition:     0.5s;
    -o-transition:      0.5s;
    transition:         0.5s;
}
a:hover,
a:focus {
    background: rgba(255,255,255,1);
    text-shadow: -1px -1px 2px rgba(100,100,100,0.5);
}

/* Fallback message */
.fallback-message {
    font-family: sans-serif;
    line-height: 1.3;

    width: 780px;
    padding: 10px 10px 0;
    margin: 20px auto;

    border: 1px solid #E4C652;
    border-radius: 10px;
    background: #EEDC94;
}

.fallback-message p {
    margin-bottom: 10px;
}

.impress-supported .fallback-message {
    display: none;
}

/* Hint message */
.hint {
    display: none;
    position: fixed;
    left: 0;
    right: 0;
    bottom: 200px;
    background: rgba(0,0,0,0.5);
    color: #EEE;
    text-align: center;
    font-size: 50px;
    padding: 20px;
    z-index: 100;
    opacity: 0;
    -webkit-transform: translateY(400px);
    -moz-transform:    translateY(400px);
    -ms-transform:     translateY(400px);
    -o-transform:      translateY(400px);
    transform:         translateY(400px);
    -webkit-transition: opacity 1s, -webkit-transform 0.5s 1s;
    -moz-transition:    opacity 1s,    -moz-transform 0.5s 1s;
    -ms-transition:     opacity 1s,     -ms-transform 0.5s 1s;
    -o-transition:      opacity 1s,      -o-transform 0.5s 1s;
    transition:         opacity 1s,         transform 0.5s 1s;
}

.impress-enabled .hint { display: block }

.impress-on-first .hint {
    opacity: 1;
    -webkit-transform: translateY(0px);
    -moz-transform:    translateY(0px);
    -ms-transform:     translateY(0px);
    -o-transform:      translateY(0px);
    transform:         translateY(0px);
    -webkit-transition: opacity 1s 5s, -webkit-transform 0.5s 4.5s;
    -moz-transition:    opacity 1s 5s,    -moz-transform 0.5s 4.5s;
    -ms-transition:     opacity 1s 5s,     -ms-transform 0.5s 4.5s;
    -o-transition:      opacity 1s 5s,      -o-transform 0.5s 4.5s;
    transition:         opacity 1s 5s,         transform 0.5s 4.5s;
}


/** Your presentation's styles **/
body {
    /* Put your font here :
    font-family: ;
    */
    min-height: 740px;

    background: rgb(215, 215, 215);
    background: -webkit-gradient(radial, 50% 50%, 0, 50% 50%, 500, from(rgb(240, 240, 240)), to(rgb(190, 190, 190)));
    background: -webkit-radial-gradient(rgb(240, 240, 240), rgb(190, 190, 190));
    background:    -moz-radial-gradient(rgb(240, 240, 240), rgb(190, 190, 190));
    background:     -ms-radial-gradient(rgb(240, 240, 240), rgb(190, 190, 190));
    background:      -o-radial-gradient(rgb(240, 240, 240), rgb(190, 190, 190));
    background:         radial-gradient(rgb(240, 240, 240), rgb(190, 190, 190));

    -webkit-transition: 0.5s;
    -moz-transition:    0.5s;
    -ms-transition:     0.5s;
    -o-transition:      0.5s;
    transition:         0.5s;

    -webkit-transform-style: preserve-3d;
    -moz-transform-style:    preserve-3d; /* Y U need this Firefox?! */
    -ms-transform-style:     preserve-3d;
    -o-transform-style:      preserve-3d;
    transform-style:         preserve-3d;
}

.impress-supported .step {
    text-align: center;
}

.impress-enabled .step {
    margin: 0;
    opacity: 0.3;

    -webkit-transition: opacity 1s;
    -moz-transition:    opacity 1s;
    -ms-transition:     opacity 1s;
    -o-transition:      opacity 1s;
    transition:         opacity 1s;
}

.impress-enabled .step.active {
    opacity: 1;
}

/* Cards? */
.step.card {
    width: 1000px;
    height: 700px;
    background: white;
    border-radius: 25px;
    box-shadow: -1px 2px 5px 1px rgba(100, 100, 100, 0.5);
    overflow: hidden;
    position: relative;
}

.step.card > h1 {
    margin-top: 70px;
    font-size: 60px;
}

.step.card > h2 {
    margin-top: 70px;
    font-size: 45px;
}

/*
.step.card > ul {
    margin-top: 125px;
    margin-left: 125px;
    text-align: left;
    list-style-type: disc;
    font-size: 160%;
    text-transform: uppercase;
}

.step.card > ul > li {
    padding-bottom: 20px;
    font-weight: normal;
}
*/

/*
.step.card > ul > li > span {
    text-transform: uppercase;
    font-weight: bold;
}

.step.card > ul > li > span:first-child {
    padding-right: 30px;
    font-size: 30px;
}
*/

.step.card p.footnote {
    font-size: 20px;
    position: absolute;
    bottom: 15px;
    width: 1000px;
    text-align: center;
    /*text-transform: uppercase;*/
    overflow: hidden;
}

EOF
fi

if [[ ! -f 'index.html' ]]; then
    echo "Create index.html"
    cat > index.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>${title}</title>
    <link rel="stylesheet" href="css/default.css" />
</head>
<body class="impress-not-supported">

<!-- Not supported? -->
<div class="fallback-message">
    <p>Your browser <b>doesn't support the features required</b> by impress.js, so you are presented with a simplified version of this presentation.</p>
    <p>For the best experience please use the latest <b>Chrome</b>, <b>Safari</b> or <b>Firefox</b> browser.</p>
</div>

<div id="impress">

    <!-- Presentation -->
    <!-- *********************************************************************************** -->

    <div id="first" class="step card">
        <h1>${title}</h1>
        <p>My First step</p>
        <p class="footnote">this is a footnote.</p>
    </div>

    <!-- *********************************************************************************** -->

</div>

<!-- Hint -->
<div class="hint">
    <p>Use a spacebar or arrow keys to navigate</p>
</div>
<script>
if ("ontouchstart" in document.documentElement) { 
    document.querySelector(".hint").innerHTML = "<p>Tap on the left or right to navigate</p>";
}
</script>

<!-- Impress :') -->
<script src="js/impress.js"></script>
<script>impress().init();</script>

</body>
</html>
EOF
fi

echo "All good! Impress now ;)"
